# Minimal configuration for Nevil-picar v2.0
# This configuration includes only the essential components

# System configuration
system:
  mode: standby
  log_level: info
  diagnostics_frequency: 0.5  # Hz

# Navigation configuration
navigation:
  mode: manual
  max_speed: 0.3  # m/s
  max_angular_speed: 1.0  # rad/s
  control_rate: 10.0  # Hz
  obstacle_avoidance: true
  path_planning: false

# Perception configuration
perception:
  enable_detection: true
  min_distance: 0.3  # m
  camera_resolution: [320, 240]  # width, height
  camera_fps: 15
  enable_object_recognition: false
  enable_lane_detection: false

# AI interfaces configuration
ai_interfaces:
  use_online_recognition: false
  use_online_tts: false
  use_cloud_ai: false
  language: en-US
  max_context_size: 5
  idle_timeout: 30.0  # seconds

# Real-time configuration
realtime:
  enable_rt: false
  isolated_core: -1
  control_priority: 0
  sensor_priority: 0
  config_priority: 0

# Simulation configuration
simulation:
  environment: empty
  use_rviz: false
  physics_update_rate: 50.0  # Hz
  visualization_update_rate: 10.0  # Hz

# Feature toggles
features:
  enable_voice_interface: false
  enable_autonomous_navigation: false
  enable_learning_mode: false
  enable_remote_control: true
  enable_data_logging: false
  enable_diagnostics: true