# Simulation configuration for Nevil-picar v2.0
# This configuration is optimized for simulation use

# System configuration
system:
  mode: standby
  log_level: debug
  diagnostics_frequency: 2.0  # Hz

# Navigation configuration
navigation:
  mode: autonomous
  max_speed: 1.0  # m/s (higher in simulation for faster testing)
  max_angular_speed: 2.0  # rad/s
  control_rate: 50.0  # Hz
  obstacle_avoidance: true
  path_planning: true

# Perception configuration
perception:
  enable_detection: true
  min_distance: 0.2  # m
  camera_resolution: [1280, 720]  # width, height (higher in simulation)
  camera_fps: 60
  enable_object_recognition: true
  enable_lane_detection: true

# AI interfaces configuration
ai_interfaces:
  use_online_recognition: true
  use_online_tts: true
  use_cloud_ai: true
  language: en-US
  max_context_size: 20
  idle_timeout: 120.0  # seconds

# Real-time configuration
realtime:
  enable_rt: false  # No need for RT in simulation
  isolated_core: -1
  control_priority: 0
  sensor_priority: 0
  config_priority: 0

# Simulation configuration
simulation:
  environment: obstacle_course  # empty, obstacle_course, maze
  use_rviz: true
  physics_update_rate: 200.0  # Hz (higher in simulation)
  visualization_update_rate: 60.0  # Hz
  enable_physics_debug: true
  enable_sensor_noise: true
  enable_actuator_noise: true
  gravity: [0.0, 0.0, -9.81]  # m/s^2
  friction_coefficient: 0.7

# Feature toggles
features:
  enable_voice_interface: true
  enable_autonomous_navigation: true
  enable_learning_mode: true
  enable_remote_control: true
  enable_data_logging: true
  enable_diagnostics: true
  enable_performance_metrics: true
  enable_visualization: true